### ISSUE TITLE
How to install bible-kjv?

### ISSUE THREAD

**Issue by kanglinyao** [camilstaps/bibletext#1]
Hi Camilstaps:
I am trying to make this package work on my Mac OS with MikTex but with no success.
How to enable -shell-escape option in TEXShop?
How to install the Bible text?

Thank you.

**Comment by camilstaps** [comment]
If there is no Mac distribution of that package you may be able to build it from source. Contact the package maintainers for that.

I don't know TEXShop so I can't help you with that either, but they probably have a support forum or something like that.
